language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: I8nC6uXgc8ZRY/0eF1+aGQLs401l26qbQOA2vluw/T2sUivWewjbK1IMASmRKhj1hGqoedEk+jdbCz/rdqsGugHi8pY0YI/YDMHx4k+NzjBAEinEjQ0pR/GRjM94OYwAXkzMtRK8KPPqRTKfOPaUt4S1KFGnNBJ7NWu6gkuwpvHy+B+RhAWurVaxKKiPmyEfMZOBnTSEke61HZPbW5djKeXdxa5I2n/9M+EKqZ4axEqZnRCE3jAetCUmrvs8EY18uq69x5vUsvjDecRdtdxo/23wXmg/BhxXXrD0IFqkiI2dqqADL2HR8A9uMirA27a5ghKb9PbKCiZ2auEn4csa+HlHW1s6oeRvyK9ujx07I4iKwZCtkNDCdotZZI2uAy68j912yldwFyM2pDlWT9q506MHubL+w6E2ZuiUluo5u0LY4SLS3/itHqAVjgQDmRLJZs4Wh2X+X/zrO5WC7WBUAt7ui6fPPSnrqKY0a78aOS/mGd+DhZFEL9cT2RB8ySP339jNFHQLHArlmZlE0Oe4PLTflQexMW7Mj+ZLz+Ztrw0Tyays/G8NTJBtwc7J+2xwtPsHHCzGpXFwVCqOBPsjL3+e9cusm3v8IbchE0rVpD1pXMjuwuDIGZgrbxbZMnIsupaCEprQwGi3sYvGdSMqPV20WXoc8i/UHx6tgJ8oGsQ=
  app: connect-the-dots-api
  on:
    repo: fishtailwrinkle/connect-the-dots-api
