language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: vsh5Fgox4gvbegHJ2YveNjLi8Y628dLNpb5BUDGOI6f5lA714MjV8BirMsw4lw1BBBxQ+QS8LXNqU9cIiUEFDFRyLcv8aYfiR4OgfqCZW//Ld0tdhE5sMogsVM6AUa9+5WS3zpLl30Te/pSwYY3rT5lSSl8tO0zs88upvE1gakczbeo7fOWLhrYiFgH5XGMivBvYi3cXBXahCp+D6k4nHMo5puUy0g9zqTnC8+urkagBJmiULcqIqm7FqPpBWsDATqYxMtzoR6tViSzuJkyyaDRtRmgzQDGpoxm7UlhGLtTqsCOIm471IuESaWfMJJbw3BzyDMhQVI78H8iDwYds26M4gOTZPWqBdOImU/Z7OfV6KcZQyDA3w+L0GnMedpJknOICskR5KGZ71ooW6JgJjU50ZFT3EJWS04pgrXUtneoTKTZymu6pXRNeEpZS7/Jq9+zmvPRcsZkKdX/E3bDuIApFcuxrDt43qdSRu/K37+VAaIGSMj+8t+zfDk/z6s1/2tT1qzOllIw4O6TlnudcgCyBTBOkVWyHZDae8qaoerdIL6352hXlCWPoehmNcXq6VhXjt6zED1T/nTfyTI3RQ1EaKQoFArF667IG39E8rkjYFvi80wyUUjZorVonKBqLYxR+r2b/xuO0Vm0bFnUZsHXePEjzhAl47ZPHP4TVkEU=
  app: connect-the-dots-api
  on:
    repo: fishtailwrinkle/connect-the-dots-api
